// Generated by `npx auth generate --yes` (see postInstall.ts), which overwrites this file with the
// real User/Session/Account/Verification table definitions read off api/src/auth/auth.ts's config.
// This placeholder only exists so that import can resolve before the first generate has run — don't
// hand-edit it, and don't add app tables here (those live in ./schema.ts, which this file doesn't
// touch and isn't touched by).
export {};
